# .github/workflows/deploy.yaml

name: Deploy to Google App Engine
on:
  push:
    branches:
      - master
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run build --if-present
      - uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
        with:
          credentials: ${{ secrets.gcp_credentials }}
      
